kind: Service
apiVersion: v1
metadata:
  name: mysql-ro
  namespace: "myns"
  labels:
    k8s-app: mysql-ro
    kubernetes.io/cluster-service: "true"
spec:
  type: ExternalName
  externalName: "readonly-externalname-changeme"

---

kind: Service
apiVersion: v1
metadata:
  name: mysql
  namespace: "myns"
  labels:
    k8s-app: mysql
    kubernetes.io/cluster-service: "true"
spec:
  type: ExternalName
  externalName: "changeme"
