apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: testapp-netpol
  namespace: myns
spec:
  podSelector:
    matchLabels:
      app: "testapp"
  policyTypes:
  - Ingress
  ingress:
  - from:
    ports:
    - protocol: TCP
      port: 8080

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: testapp-egress
  namespace: myns
spec:
  podSelector:
    matchLabels:
      app: "testapp"
  policyTypes:
  - Egress
  egress:
  - to: #Comunication with RDS
    - ipBlock:
        cidr: {{ service.aws.vpc_cidr }}
    ports:
    - protocol: TCP
      port: 3306
